name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * *"

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        run: docker compose run --rm renovate
