name: Renovate

on:
  pull_request:

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run docker ps
        run: docker ps -a
      - name: Run ls
        run: ls -la
